### ISSUE TITLE
install with android 13 not possible

### ISSUE THREAD

**Issue by mondlicht-und-sterne** [Binabh/based-cooking-app#4]
only the version 1.0.1 can be installed on my android 13, Samsung Galaxy S21 5G

version 1.0.2 cannot be installed

**Comment by Binabh** [comment]
@mondlicht-und-sterne thank you for reporting. Can you try with latest version? I have upgraded dependencies. Newest version is available in playstore and is in process for F-droid

**Comment by mondlicht-und-sterne** [comment]
@Binabh 

I don't install from gplay, so i wait to see it on F-Droid, than i install and test it.

**Comment by mondlicht-und-sterne** [comment]
Now it works
