### ISSUE TITLE
[Bug] Malformed Manifest

### ISSUE THREAD

**Issue by Rustmilian** [Binabh/based-cooking-app#6]
```
INSTALL_PARSE_FAILED_MANIFEST_MALFORMED:
Failed parse during installPackageLI:
/data/app/vmdl627376597.tmp/base.apk (at Binary XML file line #27):
mp.com.binabh.basedcooking.based_cooking.MainActivity:
Targeting S+ (version 31 and above) requires that an explicit value for android:exported be defined when intent filters are present
```

**Comment by Binabh** [comment]
@Rustmilian can you retry with latest version from source code or playstore? It should soon also be available in F-droid.
Thank you for reporting!

**Comment by Rustmilian** [comment]
@Binabh  Based Cooking (Google Play) v1.0.3 works without issue. I'll close this issue after confirming that the F-droid version is working when it releases.

**Comment by Binabh** [comment]
@Rustmilian can you confirm on F-droid? It should be working now.

**Comment by Rustmilian** [comment]
@Binabh Unfortunately v1.0.3 isn't released in the F-droid repo yet.
May I suggest submitting to [IzzyOnDroid](https://gitlab.com/IzzyOnDroid/repo/#what-are-the-requirements-an-app-must-meet-to-be-included-with-the-repo). It's faster than F-droid when it comes to releases.

**Comment by Rustmilian** [comment]
@Binabh F-droid version confirmed working.
